pip3 install sqlalchemy
apt-get install python3.7-dev
apt-get install gcc
pip3 install psutil
apt-get install postgresql-server-dev-all
pip3 install psycopg2
pip3 install flask_cors
pip3 install neo4j
pip3 install eventlet
pip3 install pymssql
pip3 install cx_Oracle
pip3 install flask_socketio
pip3 install selenium