# Generated by Django 2.2.1 on 2019-05-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sys_par',
            fields=[
                ('sys_code', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('sys_desc', models.CharField(max_length=256)),
                ('sys_value', models.CharField(max_length=256)),
                ('sys_type', models.CharField(max_length=32)),
            ],
        ),
    ]
