# Generated by Django 2.2.1 on 2019-05-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosr_back', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sys_par',
            new_name='SysPar',
        ),
    ]
