# Generated by Django 2.2.1 on 2019-05-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosr_back', '0002_auto_20190507_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_name', models.CharField(max_length=128)),
                ('user_password', models.CharField(max_length=128)),
                ('user_uuid', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MySocialTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(max_length=32)),
                ('template_uuid', models.CharField(max_length=32)),
                ('template_name', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('user_uuid', 'template_uuid')},
            },
        ),
    ]
