# Generated by Django 2.2.1 on 2019-05-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosr_back', '0003_mysocialtemplate_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_display_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
